version: "3.4"
services:
  mysqldatabase:
    image: mysql:8.0.27
    container_name: mysqldatabase
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "challenge"
      MYSQL_DATABASE: "challenge_db"
      MYSQL_USER: "challenge_usr"
      MYSQL_PASSWORD: "challenge_pass"
    ports:
      - "3306:3306"
      - "33060:33060"
    expose:
      - 3306
      - 33060
    volumes:
      - db_data:/var/lib/mysql
      - ./database/init:/docker-entrypoint-initdb.d/
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  db_data:
