apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: vguimaraes/fiap-restaurant
        resources:
          limits:
            memory: 256Mi
            cpu: 500m
        env:
          - name: ASPNETCORE_URLS
            value: http://*:5001
        ports:
        - containerPort: 5001
          name: api
        