apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysqldatabase
spec:
  selector:
    matchLabels:
      app: mysqldatabase
  template:
    metadata:
      labels:
        app: mysqldatabase
    spec:
      containers:
      - name: mysqldatabase
        image: mysql:8.0.27
        resources:
          limits:
            memory: 256Mi
            cpu: 500m
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: mysql-configmap
                key: MYSQL_ROOT_PASSWORD
          - name: MYSQL_DATABASE
            valueFrom:
              configMapKeyRef:
                name: mysql-configmap
                key: MYSQL_DATABASE
          - name: MYSQL_USER
            valueFrom:
              configMapKeyRef:
                name: mysql-configmap
                key: MYSQL_USER
          - name: MYSQL_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: mysql-configmap
                key: MYSQL_PASSWORD
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim