apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: kubernetes.io/basic-auth
stringData:
  MYSQL_ROOT_PASSWORD: "challenge"
  MYSQL_DATABASE: "challenge_db"
  MYSQL_USER: "challenge_usr"
  MYSQL_PASSWORD: "challenge_pass"