apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-configmap
  labels:
    name: mysql-configmap
data:
  MYSQL_ROOT_PASSWORD: "challenge"
  MYSQL_DATABASE: "challenge_db"
  MYSQL_USER: "challenge_usr"
  MYSQL_PASSWORD: "challenge_pass"